graph:
  input_file: "facebook"  # File di input per il grafo
  extension: "edges"

analysis:
  - name: "Degree"
    method: "get_degrees"
    proportion: null
    progress: True
  # - name: "Betweenness Centrality"
  #   method: "get_betweenness" 
  #   proportion: 0.02 
  #   progress: False
  - name: "Page Rank"
    method: "get_pagerank"
    proportion: null
    progress: True
  - name: "Clustering Coefficient"
    method: "get_clustering_coefficient"
    proportion: 0.2
    progress: True