graph:
  input_file: "TestGraph"  # File di input per il grafo
  extension: "txt" #estensione del grafo
create_new_file : False
create_new_file_random_graph : False
random_graph : True
only_random_graph : False
analysis:
  - name: "Degree"
    method: "get_degrees"
    proportion: null
    progress: True
  - name: "Betweenness Centrality"
    method: "get_betweenness" 
    proportion: null 
    progress: False
  - name: "Page Rank"
    method: "get_pagerank"
    proportion: null
    progress: True
  - name: "Friendship paradox"
    method: "get_friendship_paradox"
    proportion: null
    progress: True
